theme: jekyll-theme-minimal
logo: /logo.png
title: Logic. Execution. Graphics.
description: The LEG instruction set architecture which provides logic, execution, and graphics capabilities via a specification, simulator, and other tools.
