theme: jekyll-theme-minimal
title: Logic. Execution. Graphics.
description: The LEG instruction set architecture which provides logic, execution, and graphics cababilities via a [specification](https://github.com/L-E-G/instruction-set-architecture), simulator, and other tools.
